### ISSUE TITLE
agent设置kubesphere-service代理本地测试服务,proxy panic

### ISSUE THREAD

**Issue by mtpdx** [kubesphere/tower#39]
run agen
```bash
./bin/agent --kubeconfig ~/.kube/config --kubesphere-service http://0.0.0.0:8000 --token 13530761f40fc3161ed59316a6b3ed7b6ba44c5cca613f03d37db3fe9d903e87 --name alpha --v 4 --proxy-server http://192.168.1.31:30880
```

`http://0.0.0.0:8000`是本地的一个python文件服务 (`python3 -m http.server`)

集群pod内访问代理的80端口, proxy panic,

日志:

```
http: panic serving 10.233.124.47:41500: runtime error: invalid memory address or nil pointer dereference
goroutine 588 [running]:
net/http.(*conn).serve.func1(0xc000238280)
        /usr/local/go/src/net/http/server.go:1795 +0x139
panic(0x13594c0, 0x208c260)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/proxy.normalizeLocation(0xc000017b88, 0x20c5d60)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/proxy/upgradeaware.go:168 +0x48
k8s.io/apimachinery/pkg/util/proxy.NewUpgradeAwareHandler(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/proxy/upgradeaware.go:178
kubesphere.io/tower/pkg/proxy.(*Server).ServeHTTP(0xc000337b00, 0x16d7f80, 0xc00012a700, 0xc000260c00)
        /workspace/pkg/proxy/proxy_server.go:184 +0x28b
net/http.serverHandler.ServeHTTP(0xc0002aa380, 0x16d7f80, 0xc00012a700, 0xc000260c00)
        /usr/local/go/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc000238280, 0x16dbc40, 0xc0000a6dc0)
        /usr/local/go/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2957 +0x384

```

**Comment by FelixStarship** [comment]
应该是tower的bug、我也遇到，我是关闭了tls，直接用的http

**Comment by FelixStarship** [comment]
https://github.com/kubesphere/tower/blob/master/pkg/proxy/proxy_server.go
----------------------------------------------------------------------------------------------------
go func() {
		if s.server.TLSConfig != nil {
			if err := s.server.ListenAndServeTLS("", ""); err != nil {
				klog.Errorf("Proxy server %s: %v", s.name, err)
				close(done)
			}
		} else {
			if err := s.server.ListenAndServe(); err != nil {
				klog.Errorf("Proxy server %s: %v", s.name, err)
				close(done)
			}
		}

	}()
 s.server.ListenAndServeTLS("", "")解析 TLSConfig失败了
